import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import localFont from "next/font/local";
import Contact from "@/components/Contact/Contact";
import { GoogleAnalytics } from "nextjs-google-analytics";

export const metadata: Metadata = {
  title: "Nashville Predators",
  description: "Generated by create next app",
};

const bebasNeue = localFont({
  src: "./fonts/BebasNeue-Regular.ttf",
  variable: "--font-bebas",
  weight: "100 900",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} antialiased font-[family-name:var(--font-bebas)]`}>
        <Navbar/>
        <main>{children}</main>
        <GoogleAnalytics trackPageViews/>
        <Contact/>
      </body>
    </html>
  );
}
